### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by yochananmarqos** [sidneys/pushbullet-desktop#127]
## 🤷🏽‍♂️ Current Behaviour

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/main-process/index.js:79:35)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/app.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open amdgpu (search paths /usr/lib/dri)
failed to load driver: amdgpu
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
failed to load swrast driver
```

## 👟 Steps to Reproduce (S2R)
Install `pb-for-desktop` from the AUR (uses pacman relase) or build from source:

```
npm install
npm run build
```

## 🏡 Environmental Context
**App Version**
v11.0.2

**Operating System**
Manjaro GNOME

**Comment by baalajimaestro** [comment]
https://github.com/sidneys/pb-for-desktop/issues/110

Same as this issue, I got it fixed by setting the variable
