### ISSUE TITLE
A JavaScript error occured in the main processes

### ISSUE THREAD

**Issue by HarrisonLeece** [sidneys/pushbullet-desktop#130]
## 🤷🏽‍♂️ Current Behaviour

PB for desktop will not open its main window when 'Show PB for Desktop' is clicked from Linux tray, making the program unusable.  The error is as follows:
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: getMainWindow.show is not a function
  at click (/opt/PB for Desktop/resources/app.asar/app/scripts/main-process/menus/tray-menu.js:109:31)
  at MenuItem.click (electron/js2c/browser_init.js:1516:9)
  at Function.exectureCommand (electron/js2c/browser_init.js:1777:13)

## 🎯 Expected Behaviour

When clicking the 'Show PB for Desktop', the main menu of PB for Desktop should appear

## 👟 Steps to Reproduce (S2R)

 1. Install the debian 64 PB for Desktop and install
 2. Launch PB for Desktop
 3. Click on 'Show PB for Desktop' 

## 🏡 Environmental Context

**App Version**
v10.5.0
**Installation Type** 
Installation Manager
**Operating System**
Ubuntu 20.04 LTS 64bit

**Comment by HarrisonLeece** [comment]
Program updated to 11.0.2 and the issue was fixed.  Closing.
