### ISSUE TITLE
Can't execute program: GPU process isn't usable

### ISSUE THREAD

**Issue by Xliff** [sidneys/pushbullet-desktop#163]
## 🤷🏽‍♂️ Current Behaviour

I am getting the following error message when I attempt to start pb-for-desktop:

```
⚠️  pb-for-desktop|@sidneys/electron-updater-service | AutoUpdater not supported on Linux  0.0039 ms
[112011:0626/083029.943392:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```

## 🎯 Expected Behaviour

Usually the program runs without fail, but now I cannot get it to run.

## 👟 Steps to Reproduce (S2R)

 1. Execute `pb-for-desktop` at command prompt 
## 🏡 Environmental Context

**App Version**
v11.0.2-491
**Installation Type** 
Debian
**Operating System**
Ubuntu 22.04 LTS
Linux InfinityV 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Running w/ NVidia RTX 3070 with NVidia driver nvidia-dkms-510

**Comment by IamPhytan** [comment]
Same problem with Ubuntu 22.04
Wondering if it's related with NVidia drivers and GPU
Got same problem with normal integrated GPU

**Comment by Xliff** [comment]
I am getting the following error messages in the kernel log whenever I try to run pb-for-desktop

```
[   59.524441] traps: Chrome_IOThread[3288] trap int3 ip:55f3ed42cdf4 sp:7f1bab0824a0 error:0 in pb-for-desktop[55f3eaf9b000+5cb6000]
[   59.700802] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.700865] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.700889] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.700909] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.723657] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.723697] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.723716] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.723733] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.747279] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.747317] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.747339] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[   59.747356] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000600] Failed to grab modeset ownership
[ 3323.191807] traps: Chrome_IOThread[29973] trap int3 ip:5623ee7a1df4 sp:7f65eb14c4a0 error:0 in pb-for-desktop[5623ec310000+5cb6000]
[ 3340.474694] traps: Chrome_IOThread[30487] trap int3 ip:559a5753adf4 sp:7fdc61c634a0 error:0 in pb-for-desktop[559a550a9000+5cb6000]
```

**Comment by sdiama** [comment]
I manage to find a fix, until the developers come up with an integrated solution.

Copy the .desktop entry to you user .local folder:
`cp /usr/share/applications/pb-for-desktop.desktop ~/.local/share/applications/`

Edit the copied file, appending a --no-sandbox into the Exec command
Before: `Exec="/opt/PB for Desktop/pb-for-desktop" %U`
After: `Exec="/opt/PB for Desktop/pb-for-desktop" --no-sandbox %U`

For me it worked immediately. You may have to logout first.

**Comment by Xliff** [comment]
@sdiama  - Thanks for that! I'll try that when I get back home.

**Comment by inuonly** [comment]
Hi I am observing same behaviour. Here are some details to my environment. 
I have installed using `dpkg -i  pb-for-desktop-11.0.2-amd64.deb`
```
----------
$>sudo "/opt/PB for Desktop/pb-for-desktop" --no-sandbox
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/main-process/index.js:79:35)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/PB for Desktop/resources/app.asar/app/scripts/app.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
----------
$>"/opt/PB for Desktop/pb-for-desktop"
⚠  pb-for-desktop|@sidneys/electron-updater-service | AutoUpdater not supported on Linux  0.0062 ms
[24620:0625/233909.622346:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap
----------
environment details -
Cpu - Model name:            AMD Ryzen 5 3600 6-Core Processor
Gpu - 26:00.0 VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3070] (rev a1)
----------
uname -a
Linux tux 6.2.0-10010-tuxedo #12 SMP PREEMPT_DYNAMIC Mon Jun 12 22:06:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
----------
lsb_release -a
No LSB modules are available.
Distributor ID: Tuxedo
Description:    TUXEDO OS 2
Release:        22.04
Codename:       jammy
----------

```
Hope This helps in resolving the same.
I will also try the suggested method by "sdiama" as I have not tested that yet. Will update once i do so.

**Comment by inuonly** [comment]
Okay just now tried the method posted by "sdiama" , 
unfortunately it helps in starting the app and the app launches, but now it is stuck on connecting window once you click login or sign up at the welcome/start screen. Here is how it is stuck . 
Screen - 
![image](https://github.com/sidneys/pb-for-desktop/assets/26686197/1a6dae20-5efa-4a65-b224-96c130988ce1)

**Comment by Biccyboy** [comment]
> I manage to find a fix, until the developers come up with an integrated solution.
> 
> Copy the .desktop entry to you user .local folder: `cp /usr/share/applications/pb-for-desktop.desktop ~/.local/share/applications/`
> 
> Edit the copied file, appending a --no-sandbox into the Exec command Before: `Exec="/opt/PB for Desktop/pb-for-desktop" %U` After: `Exec="/opt/PB for Desktop/pb-for-desktop" --no-sandbox %U`
> 
> For me it worked immediately. You may have to logout first.

Can confirm it worked for me. Thank you for finding the fix.
